### ISSUE TITLE
Allow for passing in of 2 new props on MonthlyNav component

### ISSUE THREAD

**Issue by theRealScoobaSteve** [zackify/react-calendar#3]
It would be nice to have an onNextClick prop and an onPreviousClick prop.

This would be nice for making pagination-type calls for events and could probably just be called before calling onCurrentMonthChange.

It would also be nice to be able to pass in your own button component to better customize your nav. 

I could PR both these changes If you would like.

Thanks

**Comment by zackify** [comment]
This goals along with my comment on your other issue :) 

Instead of building up this library to have lots and lots of props to support everyone's individual use-cases. You are welcome to make your own `MonthlyNav` component in your codebase. 

So here is the built in one in the library:

```js
export const MonthlyNav = () => {
  let { currentMonth, onCurrentMonthChange } = useMonthlyCalendar();

  return (
    <div className="flex justify-end mb-4">
      <button
        onClick={() => onCurrentMonthChange(subMonths(currentMonth, 1))}
        className="cursor-pointer"
      >
        Previous
      </button>
      <div className="ml-4 mr-4 w-32 text-center" aria-label="Current Month">
        {format(
          currentMonth,
          getYear(currentMonth) === getYear(new Date()) ? 'LLLL' : 'LLLL yyyy'
        )}
      </div>
      <button
        onClick={() => onCurrentMonthChange(addMonths(currentMonth, 1))}
        className="cursor-pointer"
      >
        Next
      </button>
    </div>
  );
};
```

You can import the "useMonthlyCalendar" hook from this library and make a component matching what you are asking for. Now just render that in place of the <MonthlyNav/> from this library.

I'm going to close this, but feel free to reopen if you have questions.
