### ISSUE TITLE
How to modify the height into MonthlyDay

### ISSUE THREAD

**Issue by paquirus** [zackify/react-calendar#8]
Hello @zackify

how could i change the height into MonthlyDay?

Check it out
![image](https://user-images.githubusercontent.com/42079503/120055137-f2196300-bfe8-11eb-87dd-c1a5f39cf3c1.png)

i tried adding the property "className" into MonthlyBody, but it just receive "children" and "omitDays" as props.

What do you think?
Is it possible?

**Comment by zackify** [comment]
MonthlyDay is a very simple component, this library is meant to provide simple defaults, and instead of endless prop options, you can make your own component for any part of it if you wish to change it. Here's the `MonthlyDay` code:

```js
type MonthlyDayProps<DayData> = {
  renderDay: (events: DayData[]) => ReactNode;
};
export function MonthlyDay<DayData>({ renderDay }: MonthlyDayProps<DayData>) {
  let { locale } = useMonthlyCalendar();
  let { day, events } = useMonthlyBody<DayData>();
  let dayNumber = format(day, 'd', { locale });

  return (
    <div
      aria-label={`Events for day ${dayNumber}`}
      className="rc-h-48 rc-p-2 rc-border-b-2 rc-border-r-2"
    >
      <div className="rc-flex rc-justify-between">
        <div className="rc-font-bold">{dayNumber}</div>
        <div className="lg:rc-hidden rc-block">
          {format(day, 'EEEE', { locale })}
        </div>
      </div>
      <ul className="rc-divide-gray-200 rc-divide-y rc-overflow-hidden rc-max-h-36 rc-overflow-y-auto">
        {renderDay(events)}
      </ul>
    </div>
  );
}
```

You can paste this into your own app, `MyMonthlyDay` or whatever makes sense, and use it instead of the built in one. This will let you customize everything to how you want it.

This library was made with this in mind, the useMonthlyCalendar and useMonthlyBody hooks are exported for you to use.
